/**
 * runtime/scene/SceneSerializer.js
 *
 * Pure data <-> World conversion. Scene files are plain JSON so they can
 * be authored by the editor, hand-written, or generated by tools, and
 * loaded identically by the standalone runtime.
 *
 * RUNTIME-ONLY FILE.
 */

import { Transform, TRANSFORM } from "../components/Transform.js";
import { Camera, CAMERA } from "../components/Camera.js";
import { SpriteRenderer, SPRITE_RENDERER } from "../components/SpriteRenderer.js";
import { Rigidbody2D, RIGIDBODY_2D } from "../components/Rigidbody2D.js";
import { Light, LIGHT } from "../components/Light.js";

const COMPONENT_REGISTRY = {
  [TRANSFORM]: Transform,
  [CAMERA]: Camera,
  [SPRITE_RENDERER]: SpriteRenderer,
  [RIGIDBODY_2D]: Rigidbody2D,
  [LIGHT]: Light,
};

/**
 * @param {import('../core/World.js').World} world
 * @returns {object} plain JSON-serializable scene
 */
export function serializeScene(world) {
  return {
    sceneName: world.sceneName,
    entities: world.getAllEntities().map((entity) => ({
      name: entity.name,
      tag: entity.tag,
      active: entity.active,
      components: Object.fromEntries(
        Array.from(entity.components.entries()).map(([type, comp]) => [type, { ...comp }])
      ),
    })),
  };
}

/**
 * Loads scene JSON into the given World, replacing its current contents.
 * @param {import('../core/World.js').World} world
 * @param {object} sceneData
 */
export function deserializeScene(world, sceneData) {
  world.clear();
  world.sceneName = sceneData.sceneName || "Untitled Scene";

  for (const entityData of sceneData.entities || []) {
    const entity = world.createEntity(entityData.name, entityData.tag);
    entity.active = entityData.active !== false;

    for (const [type, data] of Object.entries(entityData.components || {})) {
      const ComponentClass = COMPONENT_REGISTRY[type];
      if (!ComponentClass) {
        console.warn("[SceneSerializer] Unknown component type, skipping:", type);
        continue;
      }
      entity.addComponent(type, new ComponentClass(data));
    }
  }

  return world;
}
