/**
 * runtime/scene/SceneSerializer.js
 *
 * Pure data <-> World conversion. Scene files are plain JSON so they can
 * be authored by the editor, hand-written, or generated by tools, and
 * loaded identically by the standalone runtime.
 *
 * RUNTIME-ONLY FILE.
 */

import { Transform, TRANSFORM } from "../components/Transform.js";
import { Camera, CAMERA } from "../components/Camera.js";
import { SpriteRenderer, SPRITE_RENDERER } from "../components/SpriteRenderer.js";
import { Rigidbody2D, RIGIDBODY_2D } from "../components/Rigidbody2D.js";
import { Collider2D, COLLIDER_2D } from "../components/Collider2D.js";
import { Light, LIGHT } from "../components/Light.js";
import { ShadowCaster, SHADOW_CASTER } from "../components/ShadowCaster.js";
import { CharacterController, CHARACTER_CONTROLLER } from "../components/CharacterController.js";
import { LightingSettings, LIGHTING_SETTINGS } from "../components/LightingSettings.js";
import { SpriteAnimation, SPRITE_ANIMATION } from "../components/SpriteAnimation.js";
import { AudioSource, AUDIO_SOURCE } from "../components/AudioSource.js";
import { Tileset, TILESET } from "../components/Tileset.js";
import { Tilemap, TILEMAP } from "../components/Tilemap.js";

const COMPONENT_REGISTRY = {
  [TRANSFORM]: Transform,
  [CAMERA]: Camera,
  [SPRITE_RENDERER]: SpriteRenderer,
  [RIGIDBODY_2D]: Rigidbody2D,
  [COLLIDER_2D]: Collider2D,
  [LIGHT]: Light,
  [SHADOW_CASTER]: ShadowCaster,
  [CHARACTER_CONTROLLER]: CharacterController,
  [LIGHTING_SETTINGS]: LightingSettings,
  [SPRITE_ANIMATION]: SpriteAnimation,
  [AUDIO_SOURCE]: AudioSource,
  [TILESET]: Tileset,
  [TILEMAP]: Tilemap,
};

/**
 * @param {import('../core/World.js').World} world
 * @returns {object} plain JSON-serializable scene
 */
export function serializeScene(world) {
  return {
    sceneName: world.sceneName,
    entities: world.getAllEntities().map((entity) => ({
      id: entity.id,
      name: entity.name,
      tag: entity.tag,
      active: entity.active,
      components: Object.fromEntries(
        Array.from(entity.components.entries()).map(([type, comp]) => [type, { ...comp }])
      ),
    })),
  };
}

/**
 * Loads scene JSON into the given World, replacing its current contents.
 * @param {import('../core/World.js').World} world
 * @param {object} sceneData
 */
export function deserializeScene(world, sceneData) {
  world.clear();
  world.sceneName = sceneData.sceneName || "Untitled Scene";

  for (const entityData of sceneData.entities || []) {
    const entity = world.createEntity(entityData.name, entityData.tag, entityData.id);
    entity.active = entityData.active !== false;

    for (const [type, data] of Object.entries(entityData.components || {})) {
      const ComponentClass = COMPONENT_REGISTRY[type];
      if (!ComponentClass) {
        console.warn("[SceneSerializer] Unknown component type, skipping:", type);
        continue;
      }
      entity.addComponent(type, new ComponentClass(data));
    }
  }

  return world;
}

/**
 * Serializes a single entity to plain JSON-serializable data (deep —
 * nested arrays like trianglePoints / animation clips are cloned, not
 * shared by reference with the live component). Used by the editor's
 * copy/paste; reconstruction goes through the same COMPONENT_REGISTRY
 * deserializeScene uses, so a pasted entity is identical to one loaded
 * from a scene file.
 * @param {import('../core/World.js').Entity} entity
 * @returns {{ name:string, tag:string, active:boolean, components:Record<string,object> }}
 */
export function serializeEntity(entity) {
  return {
    name: entity.name,
    tag: entity.tag,
    active: entity.active,
    components: Object.fromEntries(
      Array.from(entity.components.entries()).map(([type, comp]) => [
        type,
        JSON.parse(JSON.stringify(comp)),
      ])
    ),
  };
}

/**
 * Creates a new entity in `world` from serializeEntity output (or a
 * single entity entry from a scene file), reconstructing every
 * component via its registered constructor. Optionally overrides the
 * name (paste uses this to suffix " (Copy)"). Returns the new entity.
 * @param {import('../core/World.js').World} world
 * @param {{ name:string, tag:string, active:boolean, components:Record<string,object> }} data
 * @param {string} [nameOverride]
 * @returns {import('../core/World.js').Entity}
 */
export function instantiateEntity(world, data, nameOverride) {
  const entity = world.createEntity(nameOverride || data.name, data.tag);
  entity.active = data.active !== false;
  for (const [type, compData] of Object.entries(data.components || {})) {
    const ComponentClass = COMPONENT_REGISTRY[type];
    if (!ComponentClass) continue;
    entity.addComponent(type, new ComponentClass(JSON.parse(JSON.stringify(compData))));
  }
  return entity;
}
